films/urls.py
from django.urls import path

from . import views



urlpatterns = [
    path("", views.AllMovieView.as_view()),
    path("<slug:slug>/", views.MovieDetailView.as_view(), name='movie_detail'),
    # path("<int:pk>/", views.MovieView.as_view(), name='all_movies'),
    path("review/<int:pk>/", views.AddReview.as_view(), name='add_review'),
    path("actor/<slug:slug>/", views.ActorView.as_view(), name='actor_detail')
]

movies/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('films.urls')),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

films/models.py
from django.urls import reverse
from django.db import models
from datetime import date

from django.db.models.deletion import CASCADE


class Category(models.Model):
    name = models.CharField('Категория', max_length=150)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)


    def __str__(self):
        return self.name

    
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
    



class Actor(models.Model):
    name = models.CharField('Имя', max_length=100)
    age = models.PositiveSmallIntegerField('Возраст', default=0)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='actors/')
    slug = models.CharField("URL", max_length=160, unique=True, null=True)


    def __str__(self):
        return self.name
    

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={'slug': self.slug})

    
    class Meta:
        verbose_name = 'Актёры и Режиссёры'
        verbose_name_plural = 'Актёры и Режиссёры'




class Genre(models.Model):
    name = models.CharField('Жанр', max_length=100)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    
    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Movie(models.Model):
    title = models.CharField('Назавние', max_length=100)
    tagline = models.CharField('Слоган', max_length=100, default='')
    description = models.TextField('Описание')
    poster = models.ImageField('Постер', upload_to='movies/')
    year = models.PositiveSmallIntegerField('Дата выхода', default=2022)
    country = models.CharField('Страна', max_length=50)
    directors = models.ManyToManyField(Actor, verbose_name='Режиссёр', related_name='film_director')
    actors = models.ManyToManyField(Actor, verbose_name='Актёры', related_name='film_actors')
    genre = models.ManyToManyField(Genre, verbose_name='Жанр')
    world_premire = models.DateField('Премьера в мире', default=date.today)
    budget = models.PositiveIntegerField('Бюджет', default=0, help_text='Указывать сумму в долларах')
    fees_in_usa = models.PositiveIntegerField('Сборы в США', default=0, help_text='Указывать сумму в долларах')
    fees_in_world = models.PositiveIntegerField('Сборы в Мире', default=0, help_text='Указывать сумму в долларах')
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.SET_NULL, null=True)
    trailer = models.CharField('Трейлер', max_length=50, null=True)
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField('Черновик', default=False)



    def __str__(self):
        return self.title
    
    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)


    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={'slug': self.url})
    
    class Meta:
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'
    

class MovieShots(models.Model):
    image = models.ImageField('Изображение', upload_to='movie_shots/')
    movie = models.ForeignKey(Movie, verbose_name='Фильм', on_delete=models.CASCADE)
    


    def __str__(self):
        return self.image.url

    
    class Meta:
        verbose_name = 'Кадр из фильма'
        verbose_name_plural = 'Кадры из фильма'



class RatingStar(models.Model):
    value = models.PositiveSmallIntegerField('Значение', default=0)


    def __str__(self):
        return self.title

    
    class Meta:
        verbose_name = 'Звёзда рейтинга'
        verbose_name_plural = 'Звёзды рейтинга'


class Rating(models.Model):
    ip = models.CharField('IP адрес', max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name='Звезда')
    movie = models.ForeignKey(Movie, on_delete=CASCADE, verbose_name='Фильм')


    def __str__(self):
        return f'{self.star} - {self.movie}'

    
    class Meta:
        verbose_name = 'Рейтиг'
        verbose_name_plural = 'Рейтиги'
    


class Reviews(models.Model):
    email = models.EmailField()
    name = models.CharField('Имя', max_length=100)
    text = models.TextField('Сообщение', max_length=5000)
    parent = models.ForeignKey('self', verbose_name='Ролитель', on_delete=models.SET_NULL, blank=True, null=True)
    movie = models.ForeignKey(Movie, verbose_name='Фильм', on_delete=models.CASCADE)



    def __str__(self):
        return f'{self.name} - {self.movie}'

    
    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

films/forms.py
from django import forms

from .models import Reviews


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ("name", "text", "email")

films/views.py
from re import template
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View


from .models import Movie, Actor
from .forms import ReviewForm


class AllMovieView(ListView):
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    paginate_by = 4
    ordering = "-id"

# class MovieView(ListView):
#     model = Movie
#     queryset = Movie.objects.filter(draft=False, category=1)
#     slug_field = 'category'
#     ordering = "-id"


class MovieDetailView(DetailView):
    model = Movie
    slug_field = 'url'



class ActorView(DetailView):
    model = Actor
    template_name = "films/actor.html"




class AddReview(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())

films/templates/films/actor.html
{% extends 'films/base.html' %}
{% load humanize %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="desc1-left col-4 p-0">
                    <img src="{{ actor.image.url }}" class="img-fluid" alt="{{ movie.url }}">
                </div>
                <div class="desc1-right col-md-6 pl-lg-4">
                    <h3 class="editContent" style="outline: none; cursor: inherit;">{{ actor.name }}</h3>
                    <ul>
                        <li style="list-style: none"><span><b>Лет: </b>{{ actor.age }}</span></li>
                        <li style="list-style: none">
                            <span><b>Режиссер:</b>{% for movie in actor.film_director.all %}
                                                        {{ movie.title }}
                                                        {% if not forloop.last %},{% else %} {% endif %}
                                                    {% endfor %}
                            </span>
                        </li>
                        <li style="list-style: none"><span><b>Актёр:</b>
                            {% for movie in actor.film_actors.all %}
                                {{ movie.title }}
                                {% if not forloop.last %},{% else %} {% endif %}
                            {% endfor %}
                            </span>
                        </li>
                        <li style="list-style: none">
                            <a href="#"><b>Рейтинг:</b>
                            <span class="fa fa-star" aria-hidden="true" style="outline: none; cursor: inherit;"></span>
                                <span class="fa fa-star" aria-hidden="true" style="outline: none; cursor: inherit;"></span>
                                <span class="fa fa-star" aria-hidden="true" style="outline: none; cursor: inherit;"></span>
                                <span class="fa fa-star" aria-hidden="true" style="outline: none; cursor: inherit;"></span>
                                <span class="fa fa-star" aria-hidden="true" style="outline: none; cursor: inherit;"></span>
                                <span class="editContent" style="outline: none; cursor: inherit;">5.0</span>
                            </a>
                        </li>
                        <div class="share-desc">
                            <div class="share">
                                <h4 class="editContent" style="outline: none; cursor: inherit;">
                                    Share:</h4>
                                <ul class="w3layouts_social_list list-unstyled">
                                    <li>
                                        <a href="#" class="w3pvt_facebook editContent" style="outline: none; cursor: inherit;">
                                        <span class="fa fa-facebook-f" style="outline: none; cursor: inherit;"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="w3pvt_twitter editContent" style="outline: none; cursor: inherit;">
                                        <span class="fa fa-twitter" style="outline: none; cursor: inherit;"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="w3pvt_dribble editContent" style="outline: none; cursor: inherit;">
                                        <span class="fa fa-dribbble" style="outline: none; cursor: inherit;"></span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                </ul></div>
            </div>
            <div class="row sub-para-w3layouts mt-5">

                <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">{{ actor.name }}</h3>
                <p class="editContent" style="outline: none; cursor: inherit;">{{ actor.description }}</p>
            </div>
            <hr>
        </div>
    </div>
</div>
{% endblock %}

films/templates/films/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FilmStore</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
</head>
<body>
    {% include 'films/include/header.html' %}

        {% block content %}

        {% endblock %}

    {% include 'films/include/footer.html' %}
</body>

films/templates/films/include/footer.html
<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <section class="mb-4">
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio earum
        repellat quaerat voluptatibus placeat nam, commodi optio pariatur est quia magnam
        eum harum corrupti dicta, aliquam sequi voluptate quas.
      </p>
    </section>

  </div>

  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-white" href="/">asafm1rzoev</a>
  </div>
  <!-- Copyright -->
</footer>

films/templates/films/include/header.html
{% load movie_tags %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark  position-static mb-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">FilmStore</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        {% get_categories as categories %}
        {% for category in categories %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="/">{{ category.name }}</a>
          </li>
        {% endfor %}
      </ul>
    </div>

    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="nav-link disabled">{{ user.username }}</span> 
        </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">Выход</a>   
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Вход</a>   
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">Регистрация</a>   
          </li>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>

films/templates/films/movie_detail.html
{% extends 'films/base.html' %}
{% load humanize %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="desc1-left col-4 p-0">
                    <img src="{{ movie.poster.url }}" class="img-fluid" alt="{{ movie.url }}">
                </div>
                <div class="desc1-right col-md-6 pl-lg-4">
                    <h3 class="editContent" style="outline: none; cursor: inherit;">{{ movie.title }}</h3>
                    <ul>
                        <li style="list-style: none"><span><b>Год: </b>{{ movie.year }}</span></li>
                        <li style="list-style: none"><span><b>Страна: </b>{{ movie.country }}</span>
                        </li>
                        <li style="list-style: none"><span><b>Слоган: </b>{{ movie.tagline }}</span>
                        </li>
                        <li style="list-style: none">
                            <span><b>Режиссёры:</b>{% for director in movie.directors.all %}
                                                        <a href="{{ director.get_absolute_url }}">{{ director.name }} {% if not forloop.last %},{% else %} {% endif %}</a>
                                                    {% endfor %}
                            </span>
                        </li>
                        <li style="list-style: none"><span><b>Актеры:</b>
                            {% for actor in movie.actors.all %}
                                <a href="{{ actor.get_absolute_url }}">{{ actor.name }}{% if not forloop.last %},{% else %} {% endif %}</a>
                            {% endfor %}
                            </span>
                        </li>
                        <li style="list-style: none"><span><b>Жанр:</b>
                            {% for genre in movie.genre.all %}
                                {{ genre.name }}{% if not forloop.last %},{% else %} {% endif %}
                            {% endfor %}
                        </span>
                        </li>
                        <li style="list-style: none"><span><b>Премьера в мире:</b>{{ movie.premire }}</span>
                        </li>
                        <li style="list-style: none">
                            <span><b>Бюджет:</b> ${{ movie.budget|intcomma }}</span></li>
                        <li style="list-style: none">
                            <span><b>Сборы в США:</b> ${{ movie.fees_in_usa|intcomma }}</span></li>
                        <li style="list-style: none"><span><b>Сборы в мире:</b> ${{ movie.fees_in_world|intcomma }}</span>
                        </li>
                        <li style="list-style: none">
                            <a href="#"><b>Рейтинг:</b>
                            <span class="fa fa-star" aria-hidden="true" style="outline: none; cursor: inherit;"></span>
                                <span class="fa fa-star" aria-hidden="true" style="outline: none; cursor: inherit;"></span>
                                <span class="fa fa-star" aria-hidden="true" style="outline: none; cursor: inherit;"></span>
                                <span class="fa fa-star" aria-hidden="true" style="outline: none; cursor: inherit;"></span>
                                <span class="fa fa-star" aria-hidden="true" style="outline: none; cursor: inherit;"></span>
                                <span class="editContent" style="outline: none; cursor: inherit;">5.0</span>
                            </a>
                        </li>
                        <div class="share-desc">
                            <div class="share">
                                <h4 class="editContent" style="outline: none; cursor: inherit;">
                                    Share:</h4>
                                <ul class="w3layouts_social_list list-unstyled">
                                    <li>
                                        <a href="#" class="w3pvt_facebook editContent" style="outline: none; cursor: inherit;">
                                        <span class="fa fa-facebook-f" style="outline: none; cursor: inherit;"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="w3pvt_twitter editContent" style="outline: none; cursor: inherit;">
                                        <span class="fa fa-twitter" style="outline: none; cursor: inherit;"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="w3pvt_dribble editContent" style="outline: none; cursor: inherit;">
                                        <span class="fa fa-dribbble" style="outline: none; cursor: inherit;"></span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                </ul></div>
            </div>
            <div class="row sub-para-w3layouts mt-5">

                <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                   <u>О фильме</u> {{ movie.title }}</h3>
                <p>
                    {% for shot in movie.movieshots_set.all %}
                    <div class="desc1-left col-4 p-0">
                        <img src="{{ shot.image.url }}" class="img-fluid" alt="">
                    </div>
                    {% endfor %}
                </p>
                <p class="editContent" style="outline: none; cursor: inherit;">{{ movie.description }}</p>
                <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;"><u>Трейлер</u> {{ movie.title }}</h3>
                <p class="mt-3 italic-blue editContent" style="outline: none; cursor: inherit;">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/{{ movie.trailer }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </p>
            </div>
            <hr>
            <div class="row bg-light">
                <div class="single-form-left">
                    <!-- contact form grid -->
                    <div class="contact-single">
                        <h3 class="editContent" style="outline: none; cursor: inherit;">
                            <span class="sub-tittle editContent" style="outline: none; cursor: inherit;"></span>Оставить отзыв</h3>
                        
                        <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4" id="formReview">
                            {% csrf_token %}
                            <input type="hidden" name="parent" id="contactparent" value="">
                            <div class="form-group editContent" style="outline: none; cursor: inherit;">
                                <label for="contactcomment" class="editContent" style="outline: none; cursor: inherit;">Ваш комментарий *</label>
                                <textarea class="form-control border" rows="5" id="contactcomment" required="" name="text"></textarea>
                            </div>
                            <div class="d-sm-flex">
                                <div class="col-sm-6 form-group p-0 editContent" style="outline: none; cursor: inherit;">
                                    <label for="contactusername" class="editContent" style="outline: none; cursor: inherit;">Имя *</label>
                                    <input type="text" class="form-control border" id="contactusername" required="" name="name">
                                </div>
                                <div class="col-sm-6 form-group ml-sm-3 editContent" style="outline: none; cursor: inherit;">
                                    <label for="contactemail" class="editContent" style="outline: none; cursor: inherit;">Email *</label>
                                    <input type="email" class="form-control border" id="contactemail" required="" name="email">
                                </div>
                            </div>
                            <button type="submit" class="mt-3 btn btn-success btn-block py-3" style="outline: none; cursor: inherit;">Отправить
                            </button>
                        </form>
                    </div>
                    <!--  //contact form grid ends here -->
                </div>
                <p class="lead">Отзывов: {{ movie.reviews_set.count }}</p>

                {% for review in movie.get_review %}
                    <div class="media mt-1 py-1 bg-white rounded">
                        <div class="col-1"><img src="{% static 'user_logo.png' %}" class="mr-3 img-fluid" alt="image" style="outline: none; cursor: inherit;"></div>
                        
                        <div class="media-body mt-4">
                            <h5 class="fw-bold font-monospace" style="outline: none; cursor: inherit;">{{ review.name }}</h5>
                            <p class="mt-2 editContent" style="outline: none; cursor: inherit;">{{ review.text }}</p>
                            <a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>

                            {% for rew in review.reviews_set.all %}
                            <div class="media mt-5 editContent" style="outline: none; cursor: inherit;">
                                <div class="col-1"><img src="{% static 'user_logo.png' %}" class="mr-3 img-fluid" alt="image" style="outline: none; cursor: inherit;"></div>
                                <div class="media-body">
                                    <h5 class="mt-0 editContent" style="outline: none; cursor: inherit;">{{ rew.name }}</h5>
                                    <p class="mt-2 editContent" style="outline: none; cursor: inherit;">{{ rew.text }}</p>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<script>
    function addReview(name, id) {
        document.getElementById("contactparent").value = id;
        document.getElementById("contactcomment").value = `${name}, `
    }
</script>
{% endblock %}

films/templates/films/movie_list.html
{% extends 'films/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <a href="/"><p class="lead"><h3>Фильмы</h1></p></a>
        {% for movie in movie_list %}
            {% if movie.category.id == 1 %}
                <div class="col-2">
                    <a class="link-dark" href="{{ movie.get_absolute_url }}">
                        <div class="col-12">
                            <img src="{{ movie.poster.url }}" class="img-fluid mx-auto d-block" alt="{{ movie.url }}">
                        </div>
                        <!-- <img class="img-fluid" src="{{ movie.poster.url }}" alt="Card image cap"> -->
                        <p><h6 class="lead text-center">{{ movie.title }}</h6></p>
                    </a>
                </div> 
            {% endif %}
        {% endfor %}
    </div>
    <div class="row">
        <a href="/"><p class="lead"><h3>Сериалы</h1></p></a>
        {% for movie in movie_list %}
            {% if movie.category.id == 2 %}
                <div class="col-2">
                    <a class="link-dark" href="{{ movie.get_absolute_url }}">
                        <div class="col-12">
                            <img src="{{ movie.poster.url }}" class="img-fluid center" alt="{{ movie.url }}">
                        </div>
                        <!-- <img class="img-fluid" src="{{ movie.poster.url }}" alt="Card image cap"> -->
                        <p><h6 class="lead text-center">{{ movie.title }}</h6></p>
                    </a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}